# Local environments
"localhost":
  stage: local
  rest: http://localhost:8080/gmp/v1/

# Develop environments
"deheremap7362":
  stage: develop
  rest: http://deheremap7362:8080/gmp/v1/
'gmp\.dev\.he\.k8s\.emea\.adsint\.biz':
  stage: develop
  rest: http://gmp-ms.dev.he.k8s.emea.adsint.biz:8080/gmp/v1/

# Staging environments
"gmp.emea.adsint.biz":
  stage: staging
  rest: http://gmp.emea.adsint.biz:8080/gmp/v1/